language: c
compiler: gcc
install:
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install g++ cmake gfortran libblas-dev ggcov
  - sudo pip install pytest pep8 cpp-coveralls
script:
  - pep8 --ignore=E501 test.py
  - py.test -vv test.py
after_success:
  - coveralls --gcov /usr/bin/gcov --root --extension .F90 -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"

