language: cpp
install:
  - sudo apt-get install g++ cmake gfortran libblas-dev
  - sudo pip install pytest pep8
script:
  - pep8 --ignore=E501 update.py
  - pep8 --ignore=E501 test/test.py
  - pep8 --ignore=E501 lib/config.py
  - py.test -vv update.py
  - py.test -vv test/test.py
  - py.test -vv lib/config.py
