language: fortran
install:
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install g++ cmake gfortran libblas-dev ggcov
  - sudo pip install pytest pep8 cpp-coveralls
script:
  - cd cmake
  - wget https://github.com/scisoft/autocmake/raw/master/update.py
  - python update.py --self
  - python update.py ..
  - cd ..
  - python setup.py --fc=gfortran --static --int64 --coverage
  - cd build
  - make VERBOSE=1
  - ldd bin/example
  - cd bin
  - pwd
  - example
after_success:
  - coveralls --gcov /usr/bin/gcov  --extension .F90 -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"

notifications:
  email: false
